### ISSUE TITLE
Is it even possible to set up pixel streaming from a host behind NAT without public IP address?

### ISSUE THREAD

**Issue by Rebel028** [EpicGames/PixelStreamingInfrastructure-archived-2024#146]
What im trying to achieve is the following:

![image](https://user-images.githubusercontent.com/27502053/224103027-21c6ac54-8141-45b6-abf1-d2a29e45a133.png)
It's kind of a dumb question but is it possible to do using the tools from this repository?

The [docs](https://docs.unrealengine.com/5.1/en-US/hosting-and-networking-guide-for-pixel-streaming-in-unreal-engine/) suggest it's okay that both sides might not be able to acess each other's IP directly. That's when the TURN Server kicks in. But with the following setup pixel streaming works only if you access it through the browser on the same host machine. If you try to connect to a streamer from a different machine all you get is a message saying "WebRTC connection negotiated" in Web UI. 

According to console logs client receives IP address of a host instead of TURN relay and obviously can't establish the connection because host is behind NAT. "Force TURN" option is also doesn't help as there seem to be no turn relays in candidates list.

The setup:
- host PC with UE app and Pixel Streaming Plugin. Exists behind NAT type 2.
- Server with public IP, all necessary ports are open
- Docker container on this server, built with [Dockerfile from SignallingWebServer folder](https://github.com/EpicGames/PixelStreamingInfrastructure/blob/UE5.1/SignallingWebServer/Dockerfile) (used both 5.1 and pre-release 5.2 versions). The default entrypoint is changed to a script [Start_WithTURN_SignallingServer.sh](https://github.com/EpicGames/PixelStreamingInfrastructure/blob/UE5.1/SignallingWebServer/platform_scripts/bash/Start_WithTURN_SignallingServer.sh). All the ports (80, 443, 8888, 19303, even 19302) are published.
- Mobile and desktop browsers inside different network (also behind NAT)

Container logs says turnserver is working and its' address and credentials are passed to cirrus config but they're not seem to be used at runtime. 

What am I doing wrong?

**Comment by timbotimbo** [comment]
I've been experimenting with a fairly similar setup using the 5.0 server and sample project. 
This isn't a solution for you issue, but it might contain a hint to help you.

In my case I've got a windows desktop running both unreal and the provided signalling server.
The desktop is behind a NAT with all related ports forwarded to the pc.
I do not have a static public IP for the network, but the dynamic IP doesn't seem to change too frequently.

I will always have a single unreal instance using live link to connect to some hardware, so there is no point in hosting it in the cloud.

## 1
```
[Unreal + signalling/web server (NAT)]  <-> [STUN] <-> [clients]
```

The unreal application is launched with the public ip `-PixelStreamingIP=XXXXX` as argument.
The server is launched using `Start_SignallingServer.ps1` with the public ip in the config.
`Config: { ... , "PublicIp": "XXXXX", ... }`

This setup works for most connections by visiting the public IP,
I've found 1 cellular network so far that doesn't work.


The STUN server is a public google server automatically added to the config.

## 2
My second setup is similar but hosts the frontend remotely.

```
[Unreal + signalling server (NAT)]  <-> [Hosted frontend] <-> [STUN] <-> clients
```

To enable HTTPS I got a domain to point to the desktop public IP, this domain is used as the websocket url in the frontend.
(I got both a dynamic DNS service and a real domain to work with a Lets encrypt certificate) 

The server config disables the frontend `"UseFrontend": false` to block clients from directly visiting the Unreal pc webserver.

This gives me the same result as **1**, most connections can connect by visiting the hosted frontend.
Some cellular connections fail because they require TURN.


## 2.5
Adding the public TURN server from [openrelay](https://www.metered.ca/tools/openrelay/) in the config, made the above setups work for every connection that I've tried.
```
[Unreal + signalling/web server (NAT)]  <-> [Hosted frontend] <-> [STUN / TURN] <-> clients
```

I wouldn't rely on this public server for production or performance, but it is great as a test to see something work.
<details>
<summary> signalling server config</summary>

```
Config: {
	"UseFrontend": false,
	"UseMatchmaker": false,
	"UseHTTPS": true,
	"UseAuthentication": false,
	"LogToFile": true,
	"LogVerbose": true,
	"HomepageFile": "/Public/player.html",
	"AdditionalRoutes": {},
	"EnableWebserver": false,
	"MatchmakerAddress": "",
	"MatchmakerPort": "9999",
	"PublicIp": "XXXXXXX",
	"HttpPort": 80,
	"HttpsPort": 443,
	"StreamerPort": 8888,
	"SFUPort": 8889,
	"peerConnectionOptions": "{ \"iceServers\": [{\"urls\": [\"stun:openrelay.metered.ca:80\"]}, {\"urls\": \"turn:openrelay.metered.ca:443\",  \"username\": \"openrelayproject\", \"credential\": \"openrelayproject\"}] }"
}
```
</details>

## 
I never got `Start_WithTURN_SignallingServer.ps1` working behind the NAT, but I guess the point of the TURN server is to be outside the NAT.

Since running the signalling server locally and using remote STUN /TURN urls seem to work, my next step is hosting a STUN / TURN server somewhere.

**Comment by lukehb** [comment]
> host PC with UE app and Pixel Streaming Plugin. Exists behind NAT type 2.
> Mobile and desktop browsers inside different network (also behind NAT)

If you can't established a connection using just a STUN server, you will need to use a TURN server.

And, as @timbotimbo alludes,

> but I guess the point of the TURN server is to be outside the NAT

Yes, indeed.

**Comment by lukehb** [comment]
For the setup you are wanting to do, with public TURN server, I think the provided scripts won't be correctly configured. Basically the key important bit of information is to start the signalling server with the correct TURN address passed in. You may need to bypass the scripts altogether (or modify them) as they as mostly useful (for now...) for a setup where all components are on the same machine.

**Comment by Rebel028** [comment]
Thanks for your replies, @timbotimbo @lukehb they were both helpful and I finally got it working.
Built-in scripts are really a mess, so I left the Docker Entrypoint as is.

### Here's what I did (works for 5.1 branch at least):

I've set up `coturn` server in a separate container (it's easier to monitor it that way) by running 
```sh
docker run -d -p 3478:3478 -p 3478:3478/udp --name turnserver coturn/coturn \
 --realm=PixelStreaming -f -a -v -n -u PixelStreamingUser:AnotherTURNintheroad
``` 
(in other words, tha same command that is used to run it in a script)

And then I've modified the config file and set peerConnectionOptions to following:

```json
"peerConnectionOptions": "{ \"iceServers\": [{\"urls\": [\"stun:stun.l.google.com:19302\", \"turn:myServerIP:3478\"],\"username\":\"PixelStreamingUser\",\"credential\":\"AnotherTURNintheroad\"}] }"
```

(I'm not yet sure if STUN server is needed here but ok)

### The Most Crucial Things by now:

- TURN url/IP **must** be accessible for the final client. They're being sent to a client's browser and the client won't be able to connect to neither `turn:localhost:3478` nor `turn:172.17.0.1:3478` etc
- you **must** specify credentials for TURN server. I suppose you can launch it without any credentials but Pixel Streaming Plugin expects `peerConnectionOptions` to have username and password. Otherwise it will crash your app:
![image](https://user-images.githubusercontent.com/27502053/224831756-84088f9a-7d24-4366-a223-6d4659113831.png)

**Comment by lukehb** [comment]
@Rebel028 Great you got it working! Thanks for sharing your results. I will close this one now.
