### ISSUE TITLE
[BUG] - Mic not working

### ISSUE THREAD

**Issue by zixixr** [EpicGames/PixelStreamingInfrastructure-archived-2024#182]
**UE Version: **
UE 5.1.1

Hi I am making a multiplayer pixel streaming game, and I have implemented voice chat in the game. While the mic worked during PC to PC in Lan, it fails to work after using pixel streaming through browser.

Just want to make sure that the mic from browser is working right? Becasue I read some comment on youtube saying that the turn on mic toggle is not actually working in 5.1

**Comment by DenisTensorWorks** [comment]
Hi zixixr,

We would be very keen to hear some more information on your implementation. Here is some general information to consider about the use of the feature:

Microphone feature in Pixel Streaming simply passes the audio data from the mic back to UE, which can then be customized to be passed to a voice chat plugin. You can go in a few ways to get the audio data out of the voice plugin and feed it back into Pixel Streaming to be able to hear the other players:

- Choose a voice chat plugin whose audio data goes through the Unreal audio system, which will allow Pixel Streaming to just pick up the audio as per normal
- Complete the implementation of Pixel Streaming audio mixer and plug the audio from your voice plugin into that - see [this class](https://github.com/EpicGames/UnrealEngine/blob/release/Engine/Plugins/Media/PixelStreaming/Source/PixelStreaming/Private/AudioInputMixer.h) for a jumping in point.

Alternatively, you can modify Pixel Streaming C++ code to redirect the audio data and instead of passing it to the Unreal Engine’s audio system, pass it to your voice chat plugin. For this, you’ll need to have a look at creating your own audio sink (which is what the [Pixel Streaming audio component](https://github.com/EpicGames/UnrealEngine/blob/5ca9da84c694c6eee288c30a547fcaa1a40aed9b/Engine/Plugins/Media/PixelStreaming/Source/PixelStreaming/Public/IPixelStreamingStreamer.h#L220) does)

What was your implementation method?

**Comment by zixixr** [comment]
Hi Denis,

Thanks for the reply, i'll check with my development colleague regarding this. It's just I read many comments on this link regarding mic use in pixel streaming: https://www.youtube.com/watch?v=Z-3qY-qKbQo. They say that the mic toggle is not working so far according to epic's reply.

**Comment by zixixr** [comment]
> Hi zixixr,
> 
> We would be very keen to hear some more information on your implementation. Here is some general information to consider about the use of the feature:
> 
> Microphone feature in Pixel Streaming simply passes the audio data from the mic back to UE, which can then be customized to be passed to a voice chat plugin. You can go in a few ways to get the audio data out of the voice plugin and feed it back into Pixel Streaming to be able to hear the other players:
> 
> * Choose a voice chat plugin whose audio data goes through the Unreal audio system, which will allow Pixel Streaming to just pick up the audio as per normal
> * Complete the implementation of Pixel Streaming audio mixer and plug the audio from your voice plugin into that - see [this class](https://github.com/EpicGames/UnrealEngine/blob/release/Engine/Plugins/Media/PixelStreaming/Source/PixelStreaming/Private/AudioInputMixer.h) for a jumping in point.
> 
> Alternatively, you can modify Pixel Streaming C++ code to redirect the audio data and instead of passing it to the Unreal Engine’s audio system, pass it to your voice chat plugin. For this, you’ll need to have a look at creating your own audio sink (which is what the [Pixel Streaming audio component](https://github.com/EpicGames/UnrealEngine/blob/5ca9da84c694c6eee288c30a547fcaa1a40aed9b/Engine/Plugins/Media/PixelStreaming/Source/PixelStreaming/Public/IPixelStreamingStreamer.h#L220) does)
> 
> What was your implementation method?

It's been solved, didn't notice that useMic is only working in localhost and HTTPS. Now I could get the audio from PixelStreamingAudio Component

**Comment by Suicide09** [comment]
Does this method work for UE 4.27 also?
