### ISSUE TITLE
Microphone bug - Constant Echo and noise, and no voice in client side

### ISSUE THREAD

**Issue by FerreroDev** [EpicGames/PixelStreamingInfrastructure-archived-2024#202]
**UE Version: **
E.g. UE 5.1.1

**Problem component**
E.g. Audio issue on pixel streaming

**Description**
There is a constant background noise and the voice echoes. The clients on pixel streaming cannot input their voice even though their microphone is activated.

**Steps to Reproduce:**
Create custom events that trigger sound using the pixel streaming component.

**Expected behavior**
A constant echo and voice loop.

**Screenshots**

**Platform (please complete the following information):**
 - Browser using pixel streaming

**Comment by jimcccc** [comment]
Ok

**Comment by jimcccc** [comment]
Ok

**Comment by DenisTensorWorks** [comment]
Hi there,

Have a look at the [Microphone documentation](https://github.com/EpicGames/PixelStreamingInfrastructure/blob/master/Frontend/Docs/Using%20the%20Microphone%20Feature.md) we've recently put up, it might help answer your question.
It is normal that you would hear your own echo when the microphone is active and it is also normal that you won't hear the other clients, because the feature is not intended to pass microphone WebRTC between users.
