### ISSUE TITLE
Use Pixel Streaming Plugin from 4.27 in Unreal 5.2

### ISSUE THREAD

**Issue by lcdlv** [EpicGames/PixelStreamingInfrastructure-archived-2024#252]
Hi! In Azure you used Unreal 4.27 Pixel Streaming Signalling Server... so, if I export in unreal 5.2, my app si not compatible with the signalling server, and that makes a lot of troubles with the auto-generated infrastructure in Azure...
My idea is find a way to use the 4.27 plugin in my Unreal 5.2...
This is posible?
I tried but an Include is old, so I changed to the same in 5.2 version. After that I suppose it's failing because a plugin with the same name already exist...
If you can help me, I will appreciate!

**Comment by lukehb** [comment]
Hi @lcdlv 

> In Azure you used Unreal 4.27 Pixel Streaming Signalling Server

The Azure team maintains what is on Azure, not us. I believe they need to upgrade what they ship to be compatible with the latest PSInfra.

> My idea is find a way to use the 4.27 plugin in my Unreal 5.2... This is posible?

No, not really. There have been significant changes to UE codebase between 4.27 and 5.2, simply putting the 4.27 version of the Pixel Streaming plugin into UE 5.2 would result in many compilation issues that would have to be resolved due to underlying API changes (especially due to the changes in rendering and WebRTC between those versions). You could attempt this backport and try to modify it to use the correct calls but it is not something we have any bandwidth to assist with.

My recommendation would be to reach out to the Azure team and ask them to upgrade their offering to work with the latest PSInfra.
