### ISSUE TITLE
[Question] Routing the pixelstream

### ISSUE THREAD

**Issue by hamzaibeid** [EpicGames/PixelStreamingInfrastructure-archived-2024#296]
is it possible to add a route for the pixel stream? for example localhost:80/pixelstream

**Comment by Belchy06** [comment]
Hey @hamzaibeid,

You can most definitely change the route for the stream.

All you'd have to do is modify [this](https://github.com/EpicGames/PixelStreamingInfrastructure/blob/master/SignallingWebServer/cirrus.js#L255) line and instead of `/`, you'd have `/pixelstream` or whatever other route you'd like.

Cheers
