### ISSUE TITLE
Pixel Streaming Audio not working on IOS

### ISSUE THREAD

**Issue by reckless007** [EpicGames/PixelStreamingInfrastructure-archived-2024#30]
I have a pixel streaming application running in which we are using Linux containers to run it . There are 2 containers 1 is signaling an the other runs the project. For signaling  we are using **https://github.com/orgs/epicgames/packages/container/package/pixel-streaming-signalling-server** image .. The application seems to work fine every browser and OS , but when it comes to IOS the audio is missing. This is not specific to one single browser on IOS. Even if host it Windows server we get the same issue. Is there a fix for it ??
If yes then is the issue on the server level or the application level

**Comment by sheepsteak** [comment]
Hi, I'd been looking into this myself. The fix for this is here:

https://github.com/EpicGames/PixelStreamingInfrastructure/blob/d31bfc0e613245ad82f993e2989bea2900b25ed8/SignallingWebServer/scripts/app.js#L1007-L1014

I've tried it myself and it works on iOS. It's needed because iOS doesn't allow audio to start playing without a user interaction. The overlay is shown so the user presses the button and then it tries to start audio again.

I have no idea if this fix made it into the image you're using (I guess it didn't).

**Comment by nirajm-ethosh** [comment]
@sheepsteak Does this require projects to be built with UE 5 ? I tried this with ones built on 4.27 - it showed following error and terminated the streamer.
"LogPixelStreamingSS: <- SS: {"type":"playerConnected","playerId":"101","dataChannel":true,"sfu":false}
[2022.08.23-12.15.48:284][370]"
"LogPixelStreamingSS: Error: Unsupported message `playerConnected` received from SS"

**Comment by mentalnote** [comment]
It might not be well advertised, but we do have a UE4.27 branch in this repo which works with 4.27

**Comment by mentalnote** [comment]
> @sheepsteak Does this require projects to be built with UE 5 ? I tried this with ones built on 4.27 - it showed following error and terminated the streamer. "LogPixelStreamingSS: <- SS: {"type":"playerConnected","playerId":"101","dataChannel":true,"sfu":false} [2022.08.23-12.15.48:284][370]" "LogPixelStreamingSS: Error: Unsupported message `playerConnected` received from SS"

This is unrelated to this issue in the title. For using the 4.27 version of the engine there is a UE4.27 branch in this repository which resolves `Unsupported message` error

**Comment by Belchy06** [comment]
Hey there @reckless007,

This issue has since been fixed here in this repository with the reason for your error being explained by @sheepsteak. Unfortunately, the signalling server container images haven't been updated yet as there hasn't been an Unreal Engine release since the fix has been implemented.

You could however build your own signalling server container image based off of the Dockerfile found here: https://github.com/EpicGames/UnrealEngine/blob/release/Engine/Extras/Containers/Dockerfiles/linux/signalling-server/Dockerfile.

This file will a few modifications to get it to work for your case:
1. Delete lines 1 and 2
2. Change line 3 to `FROM node:16`
3. Update line 6 to copy your local signalling server. eg `COPY /path/to/your/SignallingWebServer /opt/SignallingWebServer`

Let us know how that goes.

**Comment by reckless007** [comment]
@Belchy06 Thanks for the solution it worked.
