### ISSUE TITLE
HELP！！！I have an exit firewall, so I need to open the port required for this plugin. However, after opening 80 and 8888, I still cannot display video streams. Is there any other port that I need to open

### ISSUE THREAD

**Issue by taotie111** [EpicGames/PixelStreamingInfrastructure-archived-2024#375]
I have an exit firewall, so I need to open the port required for this plugin. However, after opening 80 and 8888, I still cannot display video streams. Is there any other port that I need to open
![image](https://github.com/EpicGames/PixelStreamingInfrastructure/assets/44166322/629b731e-777b-4013-a130-b9d955f309e9)

**Comment by mcottontensor** [comment]
You likely can't connect because you are blocking peer to peer UDP connections. You either need to open a UDP port and attempt a peer to peer connection or open a UDP port and host a TURN server on that port to relay your traffic through.

For the peer to peer solution: 
Open some udp ports within the range 1024-65535 that are not in use, WebRTC will port scan for open ports and try to establish a peer to peer connection using the open ports. This may not always work depending on your router config/type.

For the TURN server solution:
This may be used if the p2p solution does not work. Open udp port `19303` (this can be changed if you would like to modify the script I am about to link) and then run the `SignallingWebServer/platform_scripts/cmd/Start_WithTURN_SignallingServer.ps1` script which will start the signalling server and TURN server and expose the TURN server address to the connecting user in the browser. For context a TURN server sends all media traffic through it as a relay to get around blocked ports. This comes at the cost of additional latency. 

Video example of TURN server setup: https://www.youtube.com/watch?v=E6Q_BihsqSA 
Official UE docs explaining STUN/TURN servers: https://docs.unrealengine.com/5.3/en-US/hosting-and-networking-guide-for-pixel-streaming-in-unreal-engine/#stunandturnservers
