### ISSUE TITLE
[BUG] - Full screen on IOS runs like default video player

### ISSUE THREAD

**Issue by Virovets** [EpicGames/PixelStreamingInfrastructure-archived-2024#450]
**UE Version:**
E.g. UE 5.2

**Frontend Version:**
E.g. UE5.2-0.5.3

**Problem component**
E.g. Signalling Server, Frontend, Pixel Streaming C++ plugin

**Description**
When i try to play my game on full screen i couldn't, because when i click Full Screen, game overlayed by some default mobile video player (i will add a screenshot). So all my interactions with game are blocked by this video player. I can't move, i can't do anything, just stop or run player. Please help me with it.

**Steps to Reproduce:**
1. Run app on IOS (Safari for example)
2. Click on button Full Screen

**Expected behavior**
1. Game should work as normal in full screen.

**Screenshots**
![IMG_4491](https://github.com/EpicGames/PixelStreamingInfrastructure/assets/32961106/2652bf4d-cd98-4e76-98ce-5cd48b2a6e02)

**Platform (please complete the following information):**
 - OS: IOS
 - Safari/Chrome

**Comment by Belchy06** [comment]
Hey @Virovets,

This is expected behaviour and a known limitation of Safari and webkit-based browsers for all versions less than 17.2.

However, Apple states that as of iOS 17.2, they've fully implemented the Fullscreen API so we'll need to test using that version of Safari to see if the issue is fixed. 

Cheers

**Comment by xtaraim** [comment]
hi bug are real here
