### ISSUE TITLE
文档未更新

### ISSUE THREAD

**Issue by tututu411** [EpicGames/PixelStreamingInfrastructure-archived-2024#89]
使用ue5.1，最新代码拉下来。整体界面以及代码对比4.27版本有改动。虚幻官网像素流文档未更新，需要向虚幻应用发送自定义消息未实现，文档中也没有相关描述

**Comment by tututu411** [comment]
![image](https://user-images.githubusercontent.com/65388278/218912483-2d966fae-d5ab-413e-8e10-925fc5a633b8.png)
![image](https://user-images.githubusercontent.com/65388278/218912530-f0705c59-255f-4dd1-9f43-5caa1c5e05f2.png)
最新git代码已经移除webtrcplayer.js,app.js,emitUIInteraction函数经查看已经包含在最新的player.js,但官方文档中还在使用app.js用作示例描述，可否针对player.js进行示例描述

**Comment by Belchy06** [comment]
Hi @tututu411,

As explained in the README, the master branch is our development branch and should be used with [ue5-main](https://github.com/EpicGames/UnrealEngine/tree/ue5-main).

As there hasn't been a release since UE5.1, there haven't been any documentation updates. This means that the documentation available for UE5.1 is correct for the UE5.1 branch of this repo.

If you're looking for the latest documentation, you can find some information under Frontend/Docs, but do note that they are also out of date slightly with [this](https://github.com/EpicGames/PixelStreamingInfrastructure/issues/98) issue setup to track updating them.

Overall, you can expect up to date docs to be published before UE5.2.

**Comment by tututu411** [comment]
不好意思，是我眼拙了，谢谢解答
